# Generated by Django 5.1.7 on 2025-04-02 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя животного')),
                ('age', models.FloatField(blank=True, null=True, verbose_name='Возраст')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Описание')),
                ('animal_reservation', models.BooleanField(default=False, verbose_name='Бронь')),
                ('gender', models.CharField(choices=[('М', 'Male'), ('Ж', 'Female')], max_length=2, null=True, verbose_name='Гендер')),
                ('number_animal_cage', models.PositiveIntegerField(verbose_name='Номер вольера')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Карточка животного',
                'verbose_name_plural': 'Карточки животных',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BreedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Порода')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnimalPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Фотография')),
                ('animal_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='main.animalcardmodel')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['animal_card'],
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(max_length=100, null=True, verbose_name='Имя хозяина')),
                ('phone_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='Номер телефона')),
                ('date', models.DateField(null=True, verbose_name='Дата бронивания')),
                ('animal_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='main.animalcardmodel')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='animalcardmodel',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breed', to='main.breedmodel', verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='animalcardmodel',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species', to='main.speciesmodel', verbose_name='Вид'),
        ),
    ]
