# Generated by Django 5.2 on 2025-04-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcardmodel',
            name='gender',
            field=models.CharField(choices=[('М', 'male'), ('Ж', 'female')], max_length=2, null=True, verbose_name='Гендер'),
        ),
    ]
