# Generated by Django 5.2 on 2025-04-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_animalcardmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcardmodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True, verbose_name='Гендер'),
        ),
    ]
