# Generated by Django 5.2 on 2025-04-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_animalcardmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата бронивания'),
        ),
    ]
